const actions = {
  GET_ALL_ROLE: "GET_ALL_ROLE",
  GET_ALL_ROLE_PENDING: "GET_ALL_ROLE_PENDING",
  GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",
  GET_ALL_ROLE_ERROR: "GET_ALL_ROLE_ERROR",
};
export default actions;
